language: php
matrix:
  include:
  - php: 7.1
    env: DEPENDENCIES=lowest
  - php: 7.1
    env: DEPENDENCIES=highest
  - php: 7.2
    env: DEPENDENCIES=lowest
  - php: 7.2
    env: DEPENDENCIES=highest
  - php: 7.3
    env: DEPENDENCIES=lowest
  - php: 7.3
    env: DEPENDENCIES=highest
cache:
  directories:
  - $HOME/.composer/cache
before_script:
- composer self-update
- pecl install rdkafka
- if [ "${DEPENDENCIES}" = "lowest" ]; then composer update --prefer-lowest --prefer-dist --no-interaction --no-progress; fi;
- if [ "${DEPENDENCIES}" = "highest" ]; then composer update --prefer-dist --no-interaction --no-progress; fi;
script:
- composer code-style
- composer tests-ci
after_script:
- if [ "${TRAVIS_ALLOW_FAILURE}" = false ]; then wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.0/coveralls.phar && php coveralls.phar --verbose; fi
notifications:
  email: false