sudo: required
language: php
matrix:
  include:
  - php: 7.1
  - php: 7.2
  - php: 7.3

cache:
  directories:
  - $HOME/.composer/cache
install:
- curl -L http://packages.confluent.io/deb/5.0/archive.key | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] http://packages.confluent.io/deb/5.0 stable main"
- sudo apt-get update && sudo apt-get -y install librdkafka1 librdkafka-dev
- pecl install rdkafka
before_script:
- composer self-update
- composer install
script:
- composer code-style
#- composer tests-ci
after_script:
- if [ "${TRAVIS_ALLOW_FAILURE}" = false ]; then wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.0/coveralls.phar && php coveralls.phar --verbose; fi
notifications:
  email: false